/** Design system reminder — Calm Laboratory information pages use clean editorial columns and transparent scope statements. */
import { useEffect } from "react";
import { ExternalLink } from "lucide-react";
import { AdUnit } from "@/components/AdUnit";
import { PageFrame } from "@/components/SiteShell";
import { sourceLinks } from "@/content/site";
import { useLanguage } from "@/contexts/LanguageContext";

export function AboutPage() {
  const { language } = useLanguage(); const isAr = language === "ar";
  useEffect(() => { document.title = isAr ? "عن الموقع | دليل ألوان البول" : "About | Urine Color Guide"; }, [isAr]);
  return <PageFrame><section className="info-hero"><div className="shell"><p className="eyebrow">{isAr ? "عن الدليل" : "About the guide"}</p><h1>{isAr ? "ملاحظة أوضح، لا تشخيص أسرع." : "Clearer observation, not faster diagnosis."}</h1><p className="page-lead">{isAr ? "دليل ألوان البول مساحة تثقيفية تساعدك على ربط تغير اللون بالسياق والأعراض والمصادر الموثوقة." : "Urine Color Guide is an educational space that helps connect color changes with context, symptoms, and reliable sources."}</p></div></section><AdUnit variant="inline" /><section className="shell info-columns"><div><h2>{isAr ? "منهجنا" : "Our approach"}</h2><p>{isAr ? "نستخدم لغة احتمالية مسؤولة: قد يرتبط التغير بعوامل يومية أو صحية، ولا نعامل اللون كإجابة نهائية. كلما استمر التغير أو ترافق مع أعراض، زادت أهمية التقييم المهني." : "We use responsible, conditional language: a change may relate to everyday or medical factors, and color is never treated as a final answer. Persistent changes or symptoms make professional assessment more important."}</p></div><div><h2>{isAr ? "حدود الدليل" : "The limits of this guide"}</h2><p>{isAr ? "لا يجمع الموقع بيانات صحية، ولا يصف علاجاً، ولا يقدّم تقييماً فردياً. استخدمه كنقطة بداية لمحادثة أفضل مع مقدم الرعاية." : "The site does not collect health data, prescribe treatment, or assess an individual. Use it as a starting point for a better conversation with a care professional."}</p></div></section><section className="sources-section"><div className="shell"><p className="eyebrow">{isAr ? "منابع موثوقة" : "Trusted sources"}</p><h2>{isAr ? "المصادر التي نعود إليها." : "Sources we return to."}</h2><div className="source-list">{sourceLinks.map((item) => <a key={item.url} href={item.url} target="_blank" rel="noreferrer"><span>{item.name}</span><ExternalLink size={17} /></a>)}</div></div></section></PageFrame>;
}

export function PrivacyPage() {
  const { language } = useLanguage(); const isAr = language === "ar";
  useEffect(() => { document.title = isAr ? "الخصوصية | دليل ألوان البول" : "Privacy | Urine Color Guide"; }, [isAr]);
  return <PageFrame><section className="info-hero"><div className="shell"><p className="eyebrow">{isAr ? "الخصوصية" : "Privacy"}</p><h1>{isAr ? "قراءة خاصة وواضحة." : "Private, straightforward reading."}</h1><p className="page-lead">{isAr ? "لا يطلب هذا الدليل إدخال أعراض أو معلومات صحية شخصية لتصفح محتواه." : "This guide does not ask you to enter symptoms or personal health information to read its content."}</p></div></section><AdUnit variant="inline" /><section className="shell info-columns"><div><h2>{isAr ? "بيانات التصفح" : "Browsing data"}</h2><p>{isAr ? "قد تستخدم منصة الاستضافة قياسات تقنية أساسية لتحسين التشغيل والأمان. كما قد يستخدم الموقع Google Analytics وGoogle Tag Manager وMicrosoft Clarity لفهم الاستخدام، وGoogle AdSense لعرض إعلانات قد تعتمد على ملفات تعريف ارتباط تابعة لجهات خارجية وفق إعدادات متصفحك. لا نطلب منك إدخال أعراض أو معلومات صحية شخصية، ولا نستخدم هذه الخدمات لإنشاء ملف صحي أو تقديم تشخيص." : "The hosting platform may use basic technical measurements to improve operation and security. The site may also use Google Analytics, Google Tag Manager, and Microsoft Clarity to understand usage, and Google AdSense to display ads that may rely on third-party cookies according to your browser settings. We do not ask you to enter symptoms or personal health information, and we do not use these services to create a health profile or provide a diagnosis."}</p></div><div><h2>{isAr ? "المواقع الخارجية" : "External sites"}</h2><p>{isAr ? "تأخذك روابط المصادر إلى مواقع مستقلة لديها سياسات خصوصية خاصة بها. راجع تلك السياسات قبل تقديم أي معلومات هناك." : "Source links take you to independent websites with their own privacy practices. Review those policies before providing any information there."}</p></div></section></PageFrame>;
}
